service:
  services:
    - http
    - rabbitmq

  clients:
    - smtp
    - push
    - sms

  allowed_languages:
    - BG
    - EN
    - DE
    - ES
    - DA
    - CS

  template_cache_size: 1000

  access_token_secret: 1JDNtn6AKXnUzEra58osOJsl4N4UOydB
  access_token_expiry: 3600 # 1 hour
  refresher_token_secret: aZm48TqR2tiLMpzKrfWVLu7mG20HFkpRimw415pjWyXKcE7zxYEcKz6z6H5FZMk5
  refresher_token_expiry: 604800 # 7 days

# needed only if 'http' is included in `service.services`
http_server:
  addr: :80
  master_access_token: 4Ox0MfUgDkOuWFi9XAtwTMxe2SuvYcW7VNHbUopJCXvQk6a1aI0biwmfRq7jKMCNh37fiS1dNyo5SOyWyk7qKBD9w02c7BpreJ14qKUty1Rfl2VBzDAULcUpIVAj2ekG
  access_token_expiry_time: 300 # in seconds

# needed only if 'rabbitmq' is included in `service.services`
rabbitmq:
  url: amqp://guest:guest@ns-rabbitmq:5672
  # the maximum amount of requests the service is going to process simultaneously from the respective queue
  templates_queue_name: templates
  templates_queue_max: 20
  notifications_queue_name: notifications
  notifications_queue_max: 200

# required
database:
  driver: mysql
  username: root
  password: RootestPasswordEver1234
  host: ns-database:3306
  name: TestDatabase
  pool_size: 5

# needed only if 'smtp' is included in `service.clients`
smtp:
  from_email: your-email@gmail.com
  from_password: your-password
  host: smtp.gmail.com
  port: 587

# needed only if 'sms' is included in `service.clients`
twillio:
  messaging_service_sid:
  account_sid:
  authentication_token: