service:
  use_http: yes
  use_rabbitmq: yes
http_server:
  addr: :80
rabbitmq:
  url: amqp://rabbitmq_def_user:rabbitmq_def_pass@ns-rabbitmq:5672
database:
  driver: mysql
  username: root
  password: RootestPasswordEver1234
  host: ns-database:3306
  name: TestDatabase
  pool_size: 5
smtp:
  from_email: your-email@gmail.com
  from_password: your-password
  host: smtp.gmail.com
  port: 587