service:
  use_http: yes
  use_rabbitmq: yes

  use_smtp: yes
  use_push: yes
  use_sms: yes

# needed only if `use_http` is yes
http_server:
  addr: :80
  access_token_expiry_time: 5 # in minutes
  access_token_key_length: 16

# needed only if `use_rabbitmq` is yes
rabbitmq:
  url: amqp://guest:guest@ns-rabbitmq:5672
  # the maximum amount of requests the service is going to process simultaneously from the respective queue
  templates_queue_max: 20
  notifications_queue_max: 200

# required
database:
  driver: mysql
  username: root
  password: RootestPasswordEver1234
  host: ns-database:3306
  name: TestDatabase
  pool_size: 5

# needed only if `use_smtp` is yes
smtp:
  from_email: your-email@gmail.com
  from_password: your-password
  host: smtp.gmail.com
  port: 587

# needed only if `use_sms` is yes
twillio:
  messaging_service_sid:
  account_sid:
  authentication_token: